ZONE: us-central1-a
ACCELERATOR_TYPE: nvidia-tesla-v100
ORCHESTRATOR_TYPE: gke
NETWORK_CONFIG: default_network
VM_TYPE: n1-standard-32
GKE_ENABLE_COMPACT_PLACEMENT: "false"
GPU_COUNT: "4"
GKE_NODE_POOL_COUNT: "1"
GKE_NODE_COUNT_PER_NODE_POOL: "2"
GPU_NUMBER: "4"
MODEL_SOURCE_PATH: google/flan-t5-base
CONVERTED_MODEL_UPLOAD_PATH: gs://converted_models/flan-t5-base
MODEL_NAME: flan-t5-base
INFERENCING_IMAGE_TAG: latest
NAME_PREFIX: llm-test5
PROJECT_ID: llm-containers
