apiVersion: apps/v1
kind: Deployment
metadata:
  name: $MODEL_NAME-deployment
  labels:
    app: $MODEL_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $MODEL_NAME
  template:
    metadata:
      labels:
        app: $MODEL_NAME
    spec:
      serviceAccountName: $KSA_NAME
      nodeSelector:
        cloud.google.com/gke-accelerator: "$ACCELERATOR_TYPE"
      containers:
      - name: server
        image: "$INFERENCING_IMAGE_URI:$INFERENCING_IMAGE_TAG"
        imagePullPolicy: Always
        env:
        - name: AIP_STORAGE_URI
          value: "$MODEL_SOURCE_PATH"
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 4
            memory: "$POD_MEMORY_LIMIT"
            nvidia.com/gpu: "$GPU_NUMBER"
          requests:
            cpu: 50m
            memory: 50Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 3
          failureThreshold: 10

---
apiVersion: v1
kind: Service
metadata:
  name: $MODEL_NAME
spec:
  selector:
    app: $MODEL_NAME
  ports:
  - protocol: TCP
    name: flask
    port: 5000
    targetPort: 5000
  - protocol: TCP
    name: triton
    port: 8000
    targetPort: 8000
  type: NodePort