apiVersion: batch/v1
kind: Job
metadata:
  name: convert
spec:
  template:
    spec:
      containers:
      - name: convert
        image: gcr.io/llm-containers/convert
        entrypoint: ["./convert.sh"]
        args:
        - $GPU_NUMBER
        - $MODEL_SOURCE_PATH
        - $MODEL_UPLOAD_PATH
      restartPolicy: Never